server:
  - changed-files:
      - any-glob-to-any-file:
          - "server/**"

client:
  - changed-files:
      - any-glob-to-any-file:
          - "client/**"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/*.md"

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

database:
  - changed-files:
      - any-glob-to-any-file:
          - "server/**/Migrations/**"
          - "server/**/Data/**"

api:
  - changed-files:
      - any-glob-to-any-file:
          - "server/**/Controllers/**"

models:
  - changed-files:
      - any-glob-to-any-file:
          - "server/**/Models/**"

services:
  - changed-files:
      - any-glob-to-any-file:
          - "server/**/Services/**"

ui:
  - changed-files:
      - any-glob-to-any-file:
          - "client/**/components/**"

pages:
  - changed-files:
      - any-glob-to-any-file:
          - "client/**/pages/**"

uiux:
  - changed-files:
      - any-glob-to-any-file:
          - "uiux/**"
